### ISSUE TITLE
Naming conflict with Swift Foundation

### ISSUE THREAD

**Issue by mrylmz** [JamitLabs/NewProjectTemplate-iOS#4]
The class `Progress` has a name conflict with the [`Progress` type](https://developer.apple.com/documentation/foundation/progress) in `Foundation`.

This can lead to confusions causing build issues when Progress type doesn't include the Module Prefix, especially happening on implementations of `Protocols` which have `Progress` as parameter type or return type.

My suggestion would be to rename it.

**Comment by mrylmz** [comment]
As an example [MCSessionDelegate](https://developer.apple.com/documentation/multipeerconnectivity/mcsessiondelegate/1406965-session) would lead to build issues if it was not implemented like this:

```
func session(_ session: MCSession, 
didStartReceivingResourceWithName resourceName: String, 
    fromPeer peerID: MCPeerID, 
        with progress: Foundation.Progress) { ... }
```

**Comment by Jeehut** [comment]
Progress was removed.
