### ISSUE TITLE
Naming Conflict between HandySwift.Regex and Regex.Regex in beak File

### ISSUE THREAD

**Issue by chbe89** [JamitLabs/NewProjectTemplate-iOS#5]
The class `Regex` of the Regex framework has a name conflict with the Regex type in HandySwift.

This leads to build issues when performing a `beak initialize --projectName Example`

My suggestion is to remove HandySwift from beak file to fix the issue. I will submit a pull request later.

**Comment by Jeehut** [comment]
The Regex dependency was removed in the meantime in favor of HandySwift alone.
